spring:
  application:
  name: Wallet Service

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet-db
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
